version: 2.1
orbs:
  slack: circleci/slack@3.4.2

executors:
  tap_tester:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
jobs:
  ensure_env:
    executor: tap_tester
    steps:
      - run: aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox /tmp/circleci_workspace/dev_env.sh
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -mvenv /usr/local/share/virtualenvs/tap-stripe
            source /usr/local/share/virtualenvs/tap-stripe/bin/activate
            pip install -U pip setuptools
            pip install .[test]
            mv /usr/local/share/virtualenvs/tap-stripe /tmp/circleci_workspace
      - persist_to_workspace:
          root: /tmp/circleci_workspace
          paths:
            - dev_env.sh
            - tap-stripe/*
  build_and_test:
    executor: tap_tester
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/circleci_workspace
      - run:
          name: 'pylint'
          command: |
            source /tmp/circleci_workspace/tap-stripe/bin/activate
            pylint tap_stripe -d missing-docstring,too-many-branches
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_stripe/schemas/*.json
            stitch-validate-json tap_stripe/schemas/shared/*.json
      - run:
          name: 'Unit Tests'
          command: |
            source /tmp/circleci_workspace/tap-stripe/bin/activate
            nosetests tests/unittests
      - add_ssh_keys
  integration_test:
    parameters:
      test_command:
        type: string
    executor: tap_tester
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/circleci_workspace
      - run:
          name: 'Integration Test'
          no_output_timeout: 30m
          command: |
            source /tmp/circleci_workspace/tap-stripe/bin/activate
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            source /tmp/circleci_workspace/dev_env.sh
            pip install 'stripe==2.42.0'
            << parameters.test_command >>
      - slack/notify-on-failure:
          only_for_branches: master

workflows:
  version: 2
  commit: &commit_jobs
    jobs:
      - ensure_env:
          context: circleci-user
      - build_and_test:
          context: circleci-user
          requires:
            - ensure_env
      - integration_test:
          name: "All Fields Integration Test"
          context:
            - circleci-user
          test_command: |-
            run-test --tap=/tmp/circleci_workspace/${CIRCLE_PROJECT_REPONAME} tests/test_all_fields.py
          requires:
            - build_and_test
      - integration_test:
          name: "Discovery Integration Test"
          context:
            - circleci-user
          test_command: |-
            run-test --tap=/tmp/circleci_workspace/${CIRCLE_PROJECT_REPONAME} tests/test_discovery.py
          requires:
            - "All Fields Integration Test"
      - integration_test:
          name: "Automatic Fields Integration Test"
          context:
            - circleci-user
          test_command: |-
            run-test --tap=/tmp/circleci_workspace/${CIRCLE_PROJECT_REPONAME} tests/test_automatic_fields.py
          requires:
            - "All Fields Integration Test"
      - integration_test:
          name: "Pagination Integration Test"
          context:
            - circleci-user
          test_command: |-
            run-test --tap=/tmp/circleci_workspace/${CIRCLE_PROJECT_REPONAME} tests/test_pagination.py
          requires:
            - "All Fields Integration Test"
      - integration_test:
          name: "Create Object Integration Test"
          context:
            - circleci-user
          test_command: |-
            run-test --tap=/tmp/circleci_workspace/${CIRCLE_PROJECT_REPONAME} tests/test_create_object.py
          requires:
            - "All Fields Integration Test"
      - integration_test:
          name: "Event Updates Integration Test"
          context:
            - circleci-user
          test_command: |-
            run-test --tap=/tmp/circleci_workspace/${CIRCLE_PROJECT_REPONAME} tests/test_event_updates.py
          requires:
            - "Create Object Integration Test"
      - integration_test:
          name: "Full Table Integration Test"
          context:
            - circleci-user
          test_command: |-
            run-test --tap=/tmp/circleci_workspace/${CIRCLE_PROJECT_REPONAME} tests/test_full_replication.py
          requires:
            - "Event Updates Integration Test"
      - integration_test:
          name: "Incremental Integration Test"
          context:
            - circleci-user
          test_command: |-
            run-test --tap=/tmp/circleci_workspace/${CIRCLE_PROJECT_REPONAME} tests/test_bookmarks.py
          requires:
            - "Full Table Integration Test"
      - integration_test:
          name: "Start Date Integration Test"
          context:
            - circleci-user
          test_command: |-
            run-test --tap=/tmp/circleci_workspace/${CIRCLE_PROJECT_REPONAME} tests/test_start_date.py
          requires:
            - "Incremental Integration Test"
build_daily:
    <<: *commit_jobs
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
